### ISSUE TITLE
Multiattack "reverse engineering"

### ISSUE THREAD

**Issue by Xehanort88** [BG3-Community-Library-Team/BG3-Community-Library#1]
I'm having a difficult time understanding how multiattacks work. I can tell from examining the files that they are custom-made per creature, but it seems they reference animations as lines of code, rather than per animation.

I think a good idea could be to pool knowledge on the multiattack workings.

I was wondering if there is the chance of providing more insight on how that works, and / or a template?

A template could also allow the creation of multiattacks which involve more than 2 attacks.

**Comment by khuckins** [comment]
My understanding of multiattacks is that they have specific animations to visually display that it's a multi-attack, but the actual functionality is behind the cast2[], cast3[], etc in the SpellProperties/SpellSuccess line. For example, in Target_Multiattack_Gnoll:

`data "SpellRoll" "Attack(AttackType.MeleeUnarmedAttack); Cast2[Attack(AttackType.MeleeUnarmedAttack)]; Cast3[Attack(AttackType.MeleeUnarmedAttack)]"
`

And in the base Projectile_Multiattack, Cast2[] works in SpellRoll as well:
`
data "SpellRoll" "Attack(AttackType.RangedWeaponAttack); Cast2[Attack(AttackType.RangedWeaponAttack)]"
data "SpellSuccess" "DealDamage(MainRangedWeapon, MainRangedWeaponDamageType); ExecuteWeaponFunctors(MainHand); Cast2[DealDamage(MainRangedWeapon, MainRangedWeaponDamageType); ExecuteWeaponFunctors(MainHand)]"
`

**Comment by Xehanort88** [comment]
Thanks. I wonder if they imply special animations and how much freedom is
provided with them (namely, multiattack with aura and then 2 physical
attacks).

Sent from my Samsung Galaxy smartphone and typed with big fingers on a
small touchscreen. Please excuse any typographical errors.

Il Dom 22 Nov 2020, 9:25 PM Kyle Huckins <notifications@github.com> ha
scritto:
