### ISSUE TITLE
How do icons work?

### ISSUE THREAD

**Issue by Xehanort88** [BG3-Community-Library-Team/BG3-Community-Library#10]
I've gone to explore the "icons" PAK, and sure thing, I can see the small, inventory icons, 64*64 pixels each, and the background for menu items. What I cannot seem to find is the bigger, popped-up icon for when you highlight on a item/skill, or a background skill. Has anyone else looked around for it?
[Icons.zip](https://github.com/BG3-Community-Library-Team/BG3-Community-Library/files/5596161/Icons.zip)

**Comment by ShinyHobo** [comment]
They are located in Game\Public\Game\GUI\Assets\Tooltips

**Comment by Xehanort88** [comment]
Well, I would have NEVER thought of that. Cannot lie. Will go there then, thank you very much.
