### ISSUE TITLE
Move Spellnames/Descriptions to Localization File

### ISSUE THREAD

**Issue by khuckins** [BG3-Community-Library-Team/BG3-Community-Library#13]
**Is your feature request related to a problem? Please describe.**
Now that Localization files seem to make sense, it would be good, going forward, to push other custom content to the Localization file as well.

**Describe the solution you'd like**
Move existing Spellnames and Spell Descriptions over to the localization file.

**Comment by NellsRelo** [comment]
This is covered by the update to Full Release.
