### ISSUE TITLE
Attributes exceeding cap of 20 for PCs & variations

### ISSUE THREAD

**Issue by Xehanort88** [BG3-Community-Library-Team/BG3-Community-Library#18]
So, after digging in the game files, I noticed that the cap on attributes is only a soft cap, as opposed to a hard one by the engine. I was wondering if there is any way, via script or item, to add stats to a character which do NOT count towards the imposed softcap of 20, so that when leveling up there shouldn't be false positives. While keeping the cap of 30, of course, general).

**Comment by NellsRelo** [comment]
Closing as it relates to the game during Early Access
