### ISSUE TITLE
TargetWeaknessToX Spells need a Spell Animation

### ISSUE THREAD

**Issue by NellsRelo** [BG3-Community-Library-Team/BG3-Community-Library#20]
`CL_Target_Weakness_BASE`, or the implemented versions of the spell, could do with Spell Animations. We could also leave the animation to be implemented by modders using the spells as a base for their own, but it should probably work out of the box.

**Comment by RandoRuda** [comment]
Which parts of the spell animations are missing? Is it the visual effects on the affected character, the casting or something else that escapes me right now?

**Comment by NellsRelo** [comment]
It's the SpellAnimation line itself (for example, `data "SpellAnimation" "8b8bb757-21ce-4e02-a2f3-97d55cf2f90b,,;6606c30b-be1c-4f17-ae6b-1a591c80b18c,,;f4ac302b-1569-404f-bd52-1fe443e265df,479ee5da-2967-41e1-b7d1-a94e864a5f25,79323098-edb3-4993-ba50-9b5f705e9878;e8a5c57f-855b-4227-acaa-11e8ce8d7d64,,;7bb52cd4-0b1c-4926-9165-fa92b75876a3,,;2b81c18b-9698-4262-a623-932c2bb1296d,,;0b07883a-08b8-43b6-ac18-84dc9e84ff50,,;,,;,,"` -used for `CL_Target_SkeletonFinger`.


Currently present for WeaknesToFire(and similarly implemented for Frost and Electricity):

```
new entry "CL_Target_WeaknessToFire"
type "SpellData"
using "CL_Target_Weakness_BASE"
data "Level" "2"
data "Icon" "Status_Burning"
data "DisplayName" "h261f10e1g7636g4907g9372g3657541fd224"
data "SpellProperties" "ApplyStatus(CL_STATUS_WEAKNESS_TO_FIRE, 100, 9)"
data "TooltipStatusApply" "ApplyStatus(CL_STATUS_WEAKNESS_TO_FIRE, 100, 9)"
```

**Comment by NellsRelo** [comment]
Merged into Main
