### ISSUE TITLE
More ring slots (Feature request)

### ISSUE THREAD

**Issue by Hells-Rebellion** [BG3-Community-Library-Team/BG3-Community-Library#22]
Add more armor slots into the player inventory. An example being 10 ring slots instead of the 2 that are in the game specifically. Basically a mod that allows you to have 10 rings on your ten fingers. If this is actually possible, ideally what I would hope to expect is an option for 10 ring slots, 20 ring slots... basically more freedom. 

Bugs I think one could expect would likely be rings merging into one another, basically visual, anything else I do networking not modding.  It's like a child trying to do physics. 

Thank you if you try or succeed in this. My expectations are low and hopefully I can see a nexus mod to prove me wrong

(Feel free to remove this and remake the feature request if it is inadequate)

**Comment by NellsRelo** [comment]
Not sure about how possible this is, but it's out of scope for the Community Library, as the goal for the library is to have supplemental material that other mods can utilize. This would be a cool standalone mod, though, hopefully someone can figure it out.
