### ISSUE TITLE
Ability Deterioration Passives

### ISSUE THREAD

**Issue by NellsRelo** [BG3-Community-Library-Team/BG3-Community-Library#26]
**Is your feature request related to a problem? Please describe.**
In the base game, there are hidden passives that Improve each attribute by 1. There are also two passives that deteriorate attributes - Strength and Wisdom respectively. These are implemented ingame via events relating to the Hag, but it could be worth filling out the "AbilityDeterioration" catalog of passives.

**Describe the solution you'd like**
4 new hidden passives would be made: 
- AbilityDeterioration_Charisma
- AbilityDeterioration_Constitution
- AbilityDeterioration_Dexterity
- AbilityDeterioration_Intelligence
Each would be of type PassiveData, have a Property of IsHidden, and a Boost of Ability(ATTRIBUTE, -1)

**Comment by RandoRuda** [comment]
Eralyne (of the Appearance Edit mod) has been digging into a lot of the game data for their mod. It might be worth asking them if they've noticed any other incomplete "cycles" in their dredging through the files that we could potentially complete.

**Comment by NellsRelo** [comment]
Closing for now, will revisit later, but no sign of other incomplete cycles at the moment.
