### ISSUE TITLE
Warlock style Pact weapons for different spell-casting modifiers

### ISSUE THREAD

**Issue by RandoRuda** [BG3-Community-Library-Team/BG3-Community-Library#32]
**Is your feature request related to a problem? Please describe.**
Warlock summoned/pact weapons are coded to worth with CHA, however I believe there is a desire/need to allow others to easily access something like this for the other ability scores.

**Describe the solution you'd like**
I believe the simple solution seems to be copying a variant for each ability, potentially even setting up one to use highest spell-casting modifier. 

**Describe alternatives you've considered**
N/A

**Additional context**
I've noticed a few people in the Larian Discord ask about doing something like this for their own custom classes/subclasses, so maybe there is some worth in preparing something like this rather than people remaking the wheel each time it pops up.

**Comment by NellsRelo** [comment]
Didn't test too thoroughly, but this commit should resolve having the full set: https://github.com/BG3-Community-Library-Team/BG3-Community-Library/pull/41

Keeping this open, as having one specific to highest spellcasting modifier would be neat.

**Comment by NellsRelo** [comment]
Retargeting to a future milestone until I can get a better sense of how to handle the highest spellcasting modifier in a way that isn't too cumbersome

**Comment by NellsRelo** [comment]
Latest release adds an approach that allows the player to pick their Spellcasting Modifier via a container spell + tag combination (which the tags can be implemented differently, the container spell is just a sample approach), and the included functions now look for the given tags to determine which attribute should be used for weapons that would be affected by PACT_BLADE, closing now
