### ISSUE TITLE
Disguise Self on Custom Races May Cause CTD

### ISSUE THREAD

**Issue by NellsRelo** [BG3-Community-Library-Team/BG3-Community-Library#52]
**Describe the bug**
It's been reported on the Shadar-Kai mod that dismissing a Disguise is causing a CTD. This needs further investigation.

**To Reproduce**
1. Start a game as a Shadar-Kai.
2. Cast Disguise Self, or use a scroll or Mask of Many Faces.
3. Dismiss the Disguise.

**Comment by RandoRuda** [comment]
Disguise Self and/or other similar abilities are apparently a little bit buggy. We may need to also look at the spell and how it handles things as it may be not just the custom races causing issues.

**Comment by NellsRelo** [comment]
This is fixed with the addition of tags for Shadar-Kai. Will need to investigate if this occurs for Playable Skeletons too
