### ISSUE TITLE
Keeping track of EXP after level cap?

### ISSUE THREAD

**Issue by Xehanort88** [BG3-Community-Library-Team/BG3-Community-Library#8]
So, as far as I can tell, the game DOES keep track of exp even after you hit the level cap (I hit level 4 in the Early Access and still see exp being gained).
As I am interested in adding the "boon" system of the DMG, which allows selection of a new boon after every X experience points past level 20, I'm wondering what you think about this. Of course, it would only work with respawning/custom campaigns, as Larian doesn't really do that. 

As of now the LVL 4 cap is a soft cap, as there is a limit to experience to earn, by digging in the game files. So I'm also wondering if there is a way to wipe out exp after having earned said boon, in order to be able to restart.

Most of this depends on how much is hardcoded by the engine, and we do not know that yet.

**Comment by khuckins** [comment]
This is probably a question better brought up on the official Larian Studios discord, where it can get more eyes on it
