### ISSUE TITLE
Version Bump Dummies Library

### ISSUE THREAD

**Issue by JustusW** [BG3-Community-Library-Team/BG3-Community-Library#84]
Hi there, first of thanks for the great work, really enjoying my L20 Kensei/Hexblade 😄 
Is it maybe possible to version bump the dummies library whenever you release a new one? Vortex has trouble correctly identifying the file because it's still at 2.0.4.0 while the main lib is at 2.0.4.2 now.

**Comment by NellsRelo** [comment]
Version bumped for 2.0.4.3
